name: Metrics
on:
  # 1時間に1回更新
  schedule: [{cron: "0 * * * *"}]
  # 手動実行も可能にする
  workflow_dispatch:
  # mainブランチへのプッシュ時にも実行
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # 先ほど設定したSecret
          token: ${{ secrets.METRICS_TOKEN }}

          # オプション設定
          user: otsukafuuki
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo
          
          # 言語統計（今まで使っていた top-langs に相当するもの）
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
